### PR TITLE
Fix. Ensure masked value fit to byte.

### PR DESCRIPTION
**Pull request by moteus**
See #61

### CODE REVIEW

**Comment by moteus** [comment]
Tested on [Travis](https://travis-ci.org/moteus/lua-lluv-websocket/builds/53181730)

**Comment by lipp** [comment]
I dont think this is neccassary:
  - 0>= mask[j] <= 255 is guarenteed (https://github.com/moteus/lua-websockets/blob/fix-lua52-compat/src/websocket/frame.lua#L85)
  - 0 >= original[i] <= 255 since original is returned by string.byte

Maybe i dont fully understand this, but this a hotspot and every function call at this point has its cost.

**Comment by moteus** [comment]
I also thik the same but on travis I get `lua: /usr/local/share/lua/5.1/websocket/frame.lua:45: bad argument #2 to 'schar' (invalid value)` (https://travis-ci.org/moteus/lua-lluv-websocket/builds/53169714)
And with this patch all works (https://travis-ci.org/moteus/lua-lluv-websocket/builds/53181730)

I really did not know why. For now I have only Win XP/2k3

**Comment by moteus** [comment]
I think i found problem. You unpack mask as signed value and `bxor(-XX, v)` propogate signed bits.
Now all tests passed

**Comment by lipp** [comment]
:8ball: NICE!

**Pull request merged**
