### PR TITLE
WSS Support for Sync

### PR DESCRIPTION
**Pull request by NovusTheory**
**NOTE: You verify certificate yourself, via ssl_params**

Okay, this is an **extremely** rough draft and probably will contain a lot bugs to admit, it was tested on an actual server and it seems to work fine.

I will probably start working on the other ones soon.

LuaSec dependency now required for WSS support.

If you have issues with WSS please tag me in them so I can be sure to look at them

### CODE REVIEW

**Comment by NovusTheory** [comment]
CI failed ;(

**Comment by lipp** [comment]
@NovusTheory thx! The CI must succeed though :(  Did you try to run the docker env for testing locally?

**Comment by NovusTheory** [comment]
@lipp I'll run the stuff locally and try to get the CI to pass that way it can be added in

**Comment by NovusTheory** [comment]
@lipp I tried to run a Docker test locally but it's been hours and it still hasn't completed. This for sure isn't normal?

**Comment by NovusTheory** [comment]
I did some looking at the CI build and

@lipp https://github.com/Olivine-Labs/busted/issues/202

The CI seems to be having this **exact** problem

**Comment by NovusTheory** [comment]
I looked around the files and tried to update some stuff that may be needed

**Comment by NovusTheory** [comment]
@lipp Took me a **pain** to get this but here the CI passed

**Comment by lipp** [comment]
💯  awesome! thanks a lot!

**Comment by NovusTheory** [comment]
@lipp I did some testing with this code and I changed the title to respectively say Copas does work with this Pull Request also, I'm still working on ev though which seems to be giving me some issues

```lua
local websocket = require'websocket'
local client = websocket.client.copas()

local params = {
	mode = "client",
	protocol = "sslv23",
	verify = "none",
	options = {"all"}
}


local c = coroutine.create(function()
    client:connect('wss://echo.websocket.org','echo',params)
end)

while true do
    local dead = coroutine.resume(c)
    if dead == false then
       -- Coroutine IS dead
       break
    end
end

for i = 1, 10 do
    local echo = coroutine.create(function()
        client:send('Hello')
        print(client:receive())
    end)

    while true do
        local alive = coroutine.resume(echo) 
        if not alive then
            break
        end
    end
end
```

**Pull request merged**
