### PR TITLE
let connect return subprotocol and http headers

### PR DESCRIPTION
**Pull request by lipp**

### CODE REVIEW

**Comment by lipp** [comment]
@KSDaemon tests are failing: https://travis-ci.org/lipp/lua-websockets/jobs/59211205

please look at the bottom of the log.

Could you please fix it?

sorry it took so long. getting busted working again was aweful.

**Comment by KSDaemon** [comment]
Hi! Ok, i'll take a look.

**Comment by KSDaemon** [comment]
Hi all! 
I've fixed some errors in tests. But still there will be some failing tests :( 
As i can see, that's because autobahn does not return sec-websocket-protocol header. I've run tests against wiola, and that things works. 
I don't think, that we should remove failing checks, because they are especially for checking new functionality. 
What do you think?

**Comment by KSDaemon** [comment]
Hi, @lipp! Any plans to merge or somehow proceed this issue? I have an issue in Loowy, that depends on this :( So for now, installing Loowy through luarocks fails, because lua-websockets version, published to luarocks does not contain needed fixes.

**Pull request merged**
