### PR TITLE
Secure Socket Support for ev clients

### PR DESCRIPTION
**Pull request by NovusTheory**
My last PR had apparently _stalled_ and I'm trying again after doing a fresh fork and revising upon the current working version to get Secure Socket Support for ev clients

_side note I changed param name in sync_

### CODE REVIEW

**Comment by NovusTheory** [comment]
@lipp Dang CI and Git, here is Secure Socket Support for ev clients <3

**Comment by satom99** [comment]
Was just looking through to implement this, glad you sorted it out!

**Comment by NovusTheory** [comment]
@satom99 I'm unsure when I'll add support for SSL on all variants, however can you describe the issue with not connecting after a while? I would maybe add an issue on my git instead to best tailor

**Comment by satom99** [comment]
@NovusTheory It just does not seem to connect and so _loop_'s execution stops after a while and the program dies - being socket's connection the only task added to it.
I have seen you at the _Discord API_ guild, we may discuss  there - in case am not mistaken.

**Pull request closed without merging**
